### ISSUE TITLE
server deleting user placed items on restart

### ISSUE THREAD

**Issue by mattingale** [Awbz/OneLife#62] opened 2019-02-21 23:07 UTC
im searching through the source / server settings to see if there's any options or something related to saving the server. can't seem to find it. the server is also deleting anything that i make when i ctrl-c and re-run the server. any help / fixes much appreciated. this is a great client, very easy to modify. other than this little tickle im having lol

**Comment by Awbz** [comment] 2019-02-22 00:28
This is a known issue, which is a duplicate of #23 and is likely related to my dev environment setup for cross-compiling to Windows from Linux.  The problem popped up a while ago, after one of the many kernel updates, and I haven't been bothered to track down the exact culprit yet.  

If you want a crack at fixing it, then I suspect it's related to my includes for values.h, features.h, and/or stdc-predef.h being linked to something improper.  I suspect this wouldn't be an issue if trying to compile directly on Windows with MinGW instead of cross-compiling from Linux like I'm currently doing for all 3 platforms.

As the server build I provide is mainly meant for testing/practice, it's still served that purpose.  My apologies for any inconvenience this may cause in wanting to host your own persistent server(s) on Windows, but I'll eventually get around to fixing it!  Meanwhile, it's pretty easy to host [a Linux VM](https://onehouronelife.com/forums/viewtopic.php?id=498) that shouldn't have these particular problems.

**Closed** 2019-02-22 00:30 UTC
Labels: duplicate

**Comment by Awbz** [comment] 2019-03-31 21:08
Thanks to @JustinLove's help, Windows server users should now be able to properly save their progress.

If you appreciate his efforts, please make sure to send him your love over at his Twitch channel!  https://www.twitch.tv/wondible
